### ISSUE TITLE
Hard to read docs text

### ISSUE THREAD

**Issue by timoxley** [yargs/yargs.github.io#18]
New website looks great (it is new, right?), but I have some negative feedback: 

Perhaps my eyes are getting old but I find it particularly difficult to read the text in the docs sidebar.

My key goal when visiting the site is to simply glance at the API methods looking for something that sounds like what I'm looking for – and the current design makes it difficult to quickly skim through that list.

![image](https://cloud.githubusercontent.com/assets/43438/14526968/6bc37c8c-0279-11e6-8d78-054d768d4670.png)

Some more breathing space for the sidebar would go a long way, and maybe some more contrast and or a larger font? (the whole docs section seems a little cramped, like it was designed for very a small screen)

I was going to point at lodash as an example of a similar site with higher contrast text, but it turns out their function list is also rather low contrast: 

![image](https://cloud.githubusercontent.com/assets/43438/14527262/4c81cdb8-027b-11e6-981a-5de980312ecf.png)

However, I have no problem scanning this since there's much more space around the the sidebar, which is much wider (317px vs 230px) and the font size is larger (13px vs 11px).

Also, perhaps the API methods should appear before the examples or they could appear on different pages even.

Just some thoughts, maybe it's just my eyes.  Looks great otherwise.

**Comment by bcoe** [comment]
@lrlna seems like perhaps we might want to dig into replacing the module we're using for rendering docs? I wonder if we can style it more?

**Comment by tarungarg546** [comment]
I could help if needed for any style purposes!

**Comment by craigmorrison** [comment]
Submitted PR aims to address the sizes and link colour with a bit more scoping.

The method casing issue seems to have been fixed since this was raise
<img width="741" alt="casing" src="https://user-images.githubusercontent.com/868089/161360195-03153330-8578-4c68-a494-21663d35989a.png">
d.
