### ISSUE TITLE
Accessibility: Colour Contrasting issues

### ISSUE THREAD

**Issue by Charlotteis** [yargs/yargs.github.io#20]
Hi!

I ran your main website through [tota11y](http://khan.github.io/tota11y/) and it told me you had a few contrasting issues on your website. It's a great idea to get the contrast of your colours right so people with visual difficulties have a better chance of being able to parse the site.

```
The color combination #bc6060/#f0f0f0 has a contrast ratio of 3.70, which is not sufficient.
At this size, you will need a ratio of at least 4.5.

Consider using the following foreground/background combination:
#b44c4c/#f0f0f0  /  has a ratio of 4.52 
```

Where

```html
<span class="hljs-regexp" style="color: rgb(188, 96, 96); background-color: rgba(0, 0, 0, 0);">/usr/</span>
```

is the section with the low contrast.

---

```
The color combination #ff5af7/#f0f0f0 has a contrast ratio of 2.29, which is not sufficient.
At this size, you will need a ratio of at least 4.5.

Consider using the following foreground/background combination:
#c400bd/#f0f0f0  /  has a ratio of 4.51 
```

Where:

```html
<span class="hljs-keyword" style="color: rgb(255, 90, 247); background-color: rgba(0, 0, 0, 0);">function</span>
```

is the section with the low contrast.

---

```
The color combination #2a7ae2/#fdfdfd has a contrast ratio of 4.15, which is not sufficient.
At this size, you will need a ratio of at least 4.5.

Consider using the following foreground/background combination:
#0874df/#fdfdfd  /  has a ratio of 4.51 
```

Where:

```html
<span class="username" style="color: rgb(42, 122, 226); background-color: rgba(0, 0, 0, 0);">Github</span>
```

is the section with the low contrast.

🌞

**Comment by lrlna** [comment]
@Charlotteis thanks for putting this together! I will look over some of these suggestions sometime during the week -- they are ✨ excellent ✨ . 

Could you let me know what chrome extension/other extension you used to test this, so I, too, can debug properly? 🎉

**Comment by Charlotteis** [comment]
I used [tota11y](http://khan.github.io/tota11y/).
Happy to pair on this when I see you next, too.

**Comment by bcoe** [comment]
@Charlotteis thank you so much for the help on this 👍

**Comment by lrlna** [comment]
@Charlotteis sorry this took an entire 13 days to fix. All done in #21 ✨

**Comment by Charlotteis** [comment]
13 days is pretty quick for open source. lookin good.

**Comment by bcoe** [comment]
@Charlotteis @lrlna thanks for this awesome contribution \o/ really excited by all the great things happening in the yargs project.
