### ISSUE TITLE
All capital method names

### ISSUE THREAD

**Issue by ozum** [yargs/yargs.github.io#32]
Hi,

Just a reminder, http://yargs.js.org/docs/ has listed all method names in ALL-CAPITAL letters because of the font selected.

![image](https://cloud.githubusercontent.com/assets/1497060/24390347/f978b5dc-1390-11e7-816b-8b1803860ae4.png)

OS: MacOS 10.12.2
Browser: Chrome 56

Kind Regards,

**Comment by craigmorrison** [comment]
This is corrected on the live site now.
<img width="741" alt="casing" src="https://user-images.githubusercontent.com/868089/161360146-44bb4bb9-f324-4235-b68a-36cc1c0c402f.png">

**Comment by shadowspawn** [comment]
Thanks @ozum and @craigmorrison
