### ISSUE TITLE
"Advanced Topics: Commands" are missing.

### ISSUE THREAD

**Issue by twang2218** [yargs/yargs.github.io#33]
I hit the same problem as yargs/yargs#900, the link is http://yargs.js.org/docs/advanced.md#commands , however, it's only returned 404 error.

**Comment by bcoe** [comment]
addressed in: https://github.com/yargs/yargs/pull/909/files

**Comment by alexilyaev** [comment]
@bcoe The link on the live docs still points to the old URL, leading to a 404:  
http://yargs.js.org/docs/#api-commandmodule

"Advanced Topics: Commands "  
http://yargs.js.org/docs/advanced.md#commands
