### ISSUE TITLE
Suggestion: Use accurate letter casing in documentation headers

### ISSUE THREAD

**Issue by amcasey** [yargs/yargs.github.io#37]
First, the docs are great, so thanks for that! Having said that, I would find it easier to code against them if the headers reflected the actual casing of the names, rather than being shown in uppercase. For example, the entry for showHelp is entitled SHOWHELP. No particular objections if this is closed as unnecessary (since the names appear to all be camelCase).

(Moved from https://github.com/yargs/yargs/issues/932)

**Comment by shadowspawn** [comment]
Thanks. This has been fixed. (Per #32.)
