### ISSUE TITLE
Version number is wrong

### ISSUE THREAD

**Issue by ematipico** [yargs/yargs.github.io#45]
The current version number in the website is wrong:

<img width="501" alt="Screenshot 2019-05-16 at 11 12 36" src="https://user-images.githubusercontent.com/602478/57846205-99911780-77cb-11e9-8c0c-ab9e37ddddc0.png">

It should be v13 correct?

**Comment by bcoe** [comment]
@ematipico thanks for reporting.

**Comment by shadowspawn** [comment]
Thanks. This has been fixed.
