### ISSUE TITLE
Text colors on https://yargs.js.org/docs/

### ISSUE THREAD

**Issue by andreash** [yargs/yargs.github.io#54]
At 59 my eyes may not be the best any more. If I had a free wish, I'd wish that you guys would choose different text colors on https://yargs.js.org/docs/ to increase the readability. The mint green is what nags me...

![image](https://user-images.githubusercontent.com/95178/103340991-e0598100-4a85-11eb-9281-186b84cad393.png)

**Comment by bcoe** [comment]
@andreash I agree, not enough contrast. We should fix this.
